[deploy]
bucket = 'ek-cfn-artifacts'
region = 'us-east-1'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://cloudconceptchecker.com'
EnvBackendUrl = 'https://api.cloudconceptchecker.com'
DDBMessageTable = 'CrdDdb-DynamoDBTable-K7SZ4KQFFAI8'