[deploy]
bucket = 'ek-cfn-artifacts'
region = 'us-east-1'
stack_name = 'Cruddur-DB-Cfn'

[parameters]
NetworkingStack = 'Cruddur-Network-Cfn'
ClusterStack = 'Cruddur-Cluster-Cfn'
MasterUsername = 'cruddurroot'