[deploy]
bucket = 'ek-cfn-artifacts'
region = 'us-east-1'
stack_name = 'CrdCluster'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:882139169766:certificate/9f7502db-b678-41e3-b9b0-6af937a7aa7c'
NetworkingStack = 'CrdNet'