[deploy]
bucket = 'ek-cfn-artifacts'
region = 'us-east-1'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GithubRepo = 'erdookuhwa/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "ek-codepipeline-cruddur-artifacts"
BuildSpec = 'backend-flask/buildspec.yml'