[deploy]
bucket = 'ek-cfn-artifacts'
region = 'us-east-1'
stack_name = 'Crddur-Frontend-Cfn'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:882139169766:certificate/9f7502db-b678-41e3-b9b0-6af937a7aa7c'
WwwBucketName = 'www.cloudconceptchecker.com'
RootBucketName = 'cloudconceptchecker.com'